# Generated by Django 4.0.1 on 2022-05-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T', 'Textile'), ('F', 'Footwear'), ('MN', 'Men'), ('WM', 'Women'), ('KD', 'Kids')], max_length=2, null=True),
        ),
    ]
