# Generated by Django 4.0.1 on 2022-05-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=2, null=True)),
                ('subcategory', models.CharField(default='', max_length=50, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('desc', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(default='', null=True, upload_to='images')),
            ],
        ),
    ]
