# Generated by Django 4.0.1 on 2022-05-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_productmt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productmt',
            new_name='Productpg',
        ),
    ]
