# Generated by Django 4.0.1 on 2022-05-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_productmt_productpg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpg',
            name='category',
            field=models.CharField(choices=[('T', 'Textile'), ('F', 'Footwear'), ('MN', 'Men'), ('WM', 'Women'), ('KD', 'Kids')], max_length=2, null=True),
        ),
    ]
