# Generated by Django 4.0.1 on 2022-05-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productpg',
        ),
    ]
