# Generated by Django 4.0.1 on 2022-05-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_category_customero_productpg_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerO',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productpg',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productpg',
            name='name',
        ),
        migrations.AddField(
            model_name='productpg',
            name='desc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productpg',
            name='product_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productpg',
            name='subcategory',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productpg',
            name='category',
            field=models.CharField(choices=[('T', 'Textile'), ('F', 'Footwear'), ('MN', 'Men'), ('WM', 'Women'), ('KD', 'Kids')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='productpg',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='productpg',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
